### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by Jash271** [Jash271/Django-Project-Hotel-Booking#5]
Create a Proper Documentation

**Comment by Jam-Iko** [comment]
I would like to work on this issue. Can you please assign it to me? 
Can you explain briefly what do you mean by proper documentation: should it be README with project outline and instructions for users/developers?

**Comment by Jash271** [comment]
Yes,

**Comment by Jam-Iko** [comment]
@Jash271 Did you deploy it to heroku or elsewhere? It would be good to include the link.
